name: Build PySide6 App

on:
  workflow_dispatch:  # позволяет запуск вручную из любой ветки/тэга
    inputs:
      create_release:
        type: choice
        description: "Создавать GitHub Release (true/false)"
        required: false
        default: "false"
        options: 
        - 'false'
        - 'true'

env:
  APP_NAME: passmgr
  MAIN_FILE: passmgr.py

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyside==6 bson==0.5.10 keyboard

      - name: Build app
        run: |
          pyinstaller --noconfirm --clean --onefile --windowed $MAIN_FILE --name $APP_NAME

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ env.APP_NAME }}
          path: dist/*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: inputs.create_release == 'true'

    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
